CREATE DATABASE TIENDA_ONLINE
USE TIENDA_ONLINE

CREATE TABLE usuario(

IDUSUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBREUSUARIO VARCHAR(150) NOT NULL,
NOMBRES VARCHAR(150) NOT NULL,
APELLIDOS VARCHAR(150) NOT NULL,
CONTRASEÑA VARCHAR(150) NOT NULL,
EDAD INT(2) NOT NULL,
SEXO VARCHAR(2) NOT NULL

);

CREATE TABLE productos(
IDPRODUCTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBREPRODUCTO VARCHAR(150) NOT NULL,
TALLA VARCHAR(50) NOT NULL,
CANTIDAD VARCHAR(150) NOT NULL,
PRECIO VARCHAR(150) NOT NULL,
IMG_PRODUCT VARCHAR(75) NOT NULL
);
SELECT * FROM productos